/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Latihan;
import java.text.NumberFormat;
import java.util.Locale;
/**
 *
 * @author Hannie
 */
public class Tugas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tugas.class.getName());

    /**
     * Creates new form Tugas
     */
    public Tugas() {
        initComponents();
        txtJenisLain.setEnabled(false); // Mematikan txtJenisLain saat pertama buka
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbSteril = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtJenisLain = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        cbVitamin = new javax.swing.JCheckBox();
        cmbHewan = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbAksesoris = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHasil = new javax.swing.JTextArea();
        txtTotal = new javax.swing.JTextField();
        cmbLayanan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbSteril.setText("Steril");

        jLabel2.setText("----------------------------------------------------");

        jLabel8.setText("Total                     :");

        jLabel1.setText("----------------------------------------------------");

        txtBayar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtBayar.addActionListener(this::txtBayarActionPerformed);

        jLabel7.setText("Tambahan            :");

        jLabel4.setText("Nama Pelanggan  :");

        txtKembalian.setEditable(false);
        txtKembalian.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtKembalian.addActionListener(this::txtKembalianActionPerformed);

        jLabel10.setText("Kembalian            :");

        txtJenisLain.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtJenisLain.addActionListener(this::txtJenisLainActionPerformed);

        jLabel5.setText("Jenis Hewan          :");

        btnProses.setText("PROSES");
        btnProses.addActionListener(this::btnProsesActionPerformed);

        cbVitamin.setText("Vitamin");
        cbVitamin.addActionListener(this::cbVitaminActionPerformed);

        cmbHewan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kucing", "Anjing", "Kelinci", "Ular", "Cicak", "Lainnya" }));
        cmbHewan.addActionListener(this::cmbHewanActionPerformed);

        jLabel9.setText("Bayar                    :");

        btnReset.setText("RESET");
        btnReset.addActionListener(this::btnResetActionPerformed);

        txtNama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNama.addActionListener(this::txtNamaActionPerformed);

        jLabel6.setText("Layanan                :");

        cbAksesoris.setText("Aksesoris");

        txtHasil.setColumns(20);
        txtHasil.setRows(5);
        jScrollPane1.setViewportView(txtHasil);

        txtTotal.setEditable(false);
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTotal.addActionListener(this::txtTotalActionPerformed);

        cmbLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grooming", "Pet Hotel", "Training" }));

        jLabel3.setText("PETSHOP 🐾");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnProses)
                        .addGap(70, 70, 70)
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(80, 80, 80))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbHewan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cmbLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtJenisLain, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(txtBayar)
                                    .addComponent(txtKembalian)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbVitamin)
                                    .addComponent(cbSteril)
                                    .addComponent(cbAksesoris))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtJenisLain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbVitamin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAksesoris)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSteril)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProses)
                    .addComponent(btnReset))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBayarActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianActionPerformed

    private void txtJenisLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisLainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisLainActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        try {
            String nama = txtNama.getText();
            String hewan = cmbHewan.getSelectedItem().toString();
            String layanan = cmbLayanan.getSelectedItem().toString();

            // Validasi nama
            if (nama.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Nama harus diisi!");
                return;
            }

            // Validasi hewan lainnya
            if (hewan.equals("Lainnya")) {
                hewan = txtJenisLain.getText();
                if (hewan.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Isi jenis hewan lainnya!");
                    return;
                }
            }

            int total = 0;
            String tambahan = "";

            // Harga layanan
            if (layanan.contains("Grooming")) {
                total += 55000;
            } else if (layanan.contains("Pet Hotel")) {
                total += 150000;
            } else if (layanan.contains("Training")) {
                total += 200000;
            }

            // Tambahan
            if (cbVitamin.isSelected()) {
                total += 25000;
                tambahan += "- Vitamin (25.000)\n";
            }
            if (cbAksesoris.isSelected()) {
                total += 50000;
                tambahan += "- Aksesoris (50.000)\n";
            }
            if (cbSteril.isSelected()) {
                total += 450000;
                tambahan += "- Steril (450.000)\n";
            }
            //Format Rupiah
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
            txtTotal.setText(nf.format(total));            // Validasi bayar kosong
            
            if (txtBayar.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Masukkan jumlah bayar!");
                return;
            }

            int bayar = Integer.parseInt(txtBayar.getText().replaceAll("[^0-9]", ""));

            // Validasi uang kurang
            if (bayar < total) {
                javax.swing.JOptionPane.showMessageDialog(this, "Uang tidak cukup!");
                return;
            }

            int kembalian = bayar - total;

            // Tampilkan hasil
            txtTotal.setText(nf.format(total));
            txtKembalian.setText(nf.format(kembalian));

            // STRUK
            txtHasil.setText(
                "====== STRUK PETSHOP ======\n" +
                "Nama      : " + nama + "\n" +
                "Hewan     : " + hewan + "\n" +
                "Layanan   : " + layanan + "\n" +
                "Tambahan  :\n" + (tambahan.isEmpty() ? "-" : tambahan) +
                "------------------------------------------------\n" +
                "Total     : " + nf.format(total) + "\n" +
                "Bayar     : " + nf.format(bayar) + "\n" +
                "Kembalian : " + nf.format(kembalian) + "\n" +
                "==========================="
            );

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Input bayar harus angka!");
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void cbVitaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVitaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVitaminActionPerformed

    private void cmbHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHewanActionPerformed
        if (cmbHewan.getSelectedItem().toString().equals("Lainnya")) {
            txtJenisLain.setEnabled(true);
        } else {
            txtJenisLain.setEnabled(false);
            txtJenisLain.setText("");
        }
    }//GEN-LAST:event_cmbHewanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNama.setText("");
        txtTotal.setText("");
        txtBayar.setText("");
        txtKembalian.setText("");
        txtHasil.setText("");
        txtJenisLain.setText("");

        cmbHewan.setSelectedIndex(0);
        cmbLayanan.setSelectedIndex(0);

        cbVitamin.setSelected(false);
        cbAksesoris.setSelected(false);
        cbSteril.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tugas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox cbAksesoris;
    private javax.swing.JCheckBox cbSteril;
    private javax.swing.JCheckBox cbVitamin;
    private javax.swing.JComboBox<String> cmbHewan;
    private javax.swing.JComboBox<String> cmbLayanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextArea txtHasil;
    private javax.swing.JTextField txtJenisLain;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
